
server:
  port: 9001

spring:
  application:
   name: spring-db202507
  datasource:
    url: jdbc:mariadb://localhost:3306/spring_study
    username: root
    password: mariadb
# ?? ??? ???? db? ????? ????? ?????.

logging:
  level:
    root: INFO
    com.spring.database: DEBUG

# MyBatis Setting
mybatis:
  # SQL file location
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

  #type-aliases-package: com.spring.database
