
server:
  port: 9001

spring:
  application:
   name: spring-db202507
  datasource:
    url: jdbc:mariadb://localhost:3306/spring_study?characterEncoding=utf8mb4&serverTimezone=Asia/Seoul
    username: root
    password: mariadb
  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
  #Mapping을 위한 db의 언어를 지정
    hibernate:
      ddl-auto: update # 실무에서는 위험해서 ddl-auto를 사용하지 않음 그냥 sql에서 만들고 시작함
      # update  기존 테이블을 유지하되 변경사항이 있으면 변경
      # ddl-auto: create 기존의 테이블이 있다면 지우고 매번 새로운 테이블을 생성
    properties:
      hibernate:
        format_sql: true #sql을 한줄로 안쓰고 세로로 써주는 옵션
    database: mysql
logging:
  level:
    root: INFO
    com.spring.database: DEBUG
    org: #SQL 로그를 찍기위한 설정
      hibernate:
        SQL: debug

# MyBatis Setting
mybatis:
  # SQL file location
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.spring.database.chap03
